[tool.poetry]
name = "hypyp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
mne = "^0.20.0"
joblib = "^0.14.1"
scikit-learn = "^0.22.2"
autoreject = "^0.2.1"
matplotlib = "^3.2.1"
pandas = "^1.0.3"
numpy = "^1.18.3"
astropy = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
mkdocs = "^1.1"
mkdocstrings = "^0.10.3"
mkdocs-material = "^5.1.1"
pylint = "^2.4.4"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
